### ISSUE TITLE
Feature: Usernames shouldn't be case sensitive

### ISSUE THREAD

**Issue by chriskewl** [retrocomputacion/retrobbs#11]
When creating a new user you are allowed to type your name however you want, this is a problem with security.

Let's say I am "KiLoKaHn" and someone else comes in as "kilokahn" or "Kilokahn", they could hop into IRC or boards and pretend to be me. That would be concerning.

Suggestion is to lowercase the name when it comes in but allow a vanity spelling field. So I could go and say my name is "KiLoKaHn" and in the tinydb JSON it'll say:

```
"uname": "kilokahn",
"vname": "KiLoKaHn",
```

Now any time my name is shown in the software it could be the vname (virtual name) [KiLoKaHn], including in IRC and boards. Our login will just care about uname matching the all lowercase version [kilokahn]. 

This will solve the same user check, now you are just matching what they type in, lowercase it, then search the user records.

**Comment by chriskewl** [comment]
I changed the title because this isn't a bug but really a feature that needs added for security. Since you are salting the passwords this method will also allow us to standardize usernames.

**Comment by retrocomputacion** [comment]
Agree, I will go for keeping the usernames stored as case sensitive, but use them as not case sensitive in the database queries.

**Comment by retrocomputacion** [comment]
Commited update: Case-insensitive usernames + some UI improvements in dbmaintenance.py
