### ISSUE TITLE
Feature: Choose how many simultaneous connections are allowed

### ISSUE THREAD

**Issue by chriskewl** [retrocomputacion/retrobbs#12]
When we start talking about single-board computers such as the Raspberry Pi or Orange Pi we need to think of how many simultaneous connections are possible.

I feel comfortable with 4 simultaneous connections on a Raspberry Pi 4, that is determined on watching connections and seeing the CPU draw. 

What I would do is have an option on the config.ini:

`slots=4 ;how many connections allowed at same time`

This way it makes it easier for us to ensure we are not overloading our systems. Thanks!

**Comment by retrocomputacion** [comment]
Added in [1d5850d](https://github.com/retrocomputacion/retrobbs/commit/1d5850d41354718a56ba0248f5ed4d3ab98fbddc)
Two new configuration parameters for the [MAIN] section:
`lines`: number of simultaneous connections
`busy`: message to show when all the 'lines' are busy
