### ISSUE TITLE
Feature: Allow default weather search on config.ini

### ISSUE THREAD

**Issue by chriskewl** [retrocomputacion/retrobbs#13]
Currently when I boot up the instance the weather defaults to Greenwich (I think). I think a config.ini option of the default location on boot should be possible.

`defaultwx = Dallas, TX ;wx means Weather`

This way I can at least show the weather where I am located.

**Comment by retrocomputacion** [comment]
Added in https://github.com/retrocomputacion/retrobbs/commit/1b2ab830fd9531be1d6271ba5fdbed12eaa6e0c5
