### ISSUE TITLE
Turn off the sound of the characters on the screen

### ISSUE THREAD

**Issue by FabianClub** [retrocomputacion/retrobbs#2]
In the Commodore 64 version, it beeps with each character displayed on the screen. This sound is nice, but after a while of listening to the sound repeatedly, it becomes annoying. I request if you can please add an option to deactivate said beep and be able to activate it on another occasion, as the user wishes. From already thank you very much.

**Comment by retrocomputacion** [comment]
This issue is for Retroterm, not RetroBBS.
Retroterm already has that feature, press <commodore+m> to toggle the sound from the incoming characters.
