### ISSUE TITLE
Feature: Allow for text-only blocks in menus

### ISSUE THREAD

**Issue by chriskewl** [retrocomputacion/retrobbs#20]
In the Two-Minute Danger Theater menu I'd like a text box explaining what it is. Right now I am forced to put a "key" even though I don't want any menu action in this box.

```
[MENU10SECTION1]
title = About
entries = 1
columns = 1
entry1key = _
entry1func  = SWITCHMENU
entry1id    = 10
entry1title = 
entry1desc  = A serialized comedy series from the troupe TwistedMojo.
```

It would be nice if it will detect that it's just a text box IF no key is listed so this is my config instead:

```
[MENU10SECTION1]
title = About
entries = 1
entry1title = 
entry1desc  = A serialized comedy series from the troupe TwistedMojo.
```

**Comment by chriskewl** [comment]
It looks a little different but close enough...

[MENU10SECTION1]
title =
entries = 1

entry1func  = LABEL
entry1title = Welcome to Callin' Oates
entry1desc  = Your emergency Hall & Oates helpline.

Currently still a small bug with the entryXtitle where a border color is not correct.

**Comment by retrocomputacion** [comment]
> Currently still a small bug with the entryXtitle where a border color is not correct.

That should be fixed now
