### ISSUE TITLE
Apostrophes in Filenames Give Odd Results

### ISSUE THREAD

**Issue by chriskewl** [retrocomputacion/retrobbs#24]
I have files for Two Minute - Blake Diamond that has apostrophes:

```
King Tetachi’s Ruby 1.mp3
King Tetachi’s Ruby 2.mp3
...
King Tetachi’s Ruby 8.mp3
```

However on RetroBBS it shows:

```
King Tetachis Ruby
King Tetachis Ruby
...
King Tetachis Ruby
```

It removed the apostrophe and it stripped the number off the end of the file.

**Comment by retrocomputacion** [comment]
Fixed in [3077ddc](https://github.com/bozimmerman/Zimodem/commit/3077ddc662d5c409e8efcdd320a87adc8cfaa3bf)
