### ISSUE TITLE
Exit message not aligned

### ISSUE THREAD

**Issue by emanuelelaface** [retrocomputacion/retrobbs#35]
I think that the line `conn.SendTML(f'<DEL n=23><LTGREEN>{l_str[0]}<WHITE><PAUSE n=1>')` should be `conn.SendTML(f'<DEL n=22><LTGREEN>{l_str[0]}<WHITE><PAUSE n=1>')` because the message appears shifted of one char (at least on C64).

**Comment by retrocomputacion** [comment]
Ah yes, the number of deletes shouldn't be hard-coded like it is now.
It should take into account both the length of the menu prompt and the title for the logout option.

**Comment by retrocomputacion** [comment]
Please check if [cb3dc51](https://github.com/retrocomputacion/retrobbs/commit/cb3dc519e4606e3a435880fa321ee700b6c2a4f3) fixes the issue

**Comment by emanuelelaface** [comment]
this fixes perfectly, thanks!
