### ISSUE TITLE
TML Suggestions and a Question

### ISSUE THREAD

**Issue by eightbitswide** [retrocomputacion/retrobbs#36]
I'm using the RetroBBS system as a platform for short story publishing.  The .TML format is 98% perfect for what I'm trying to accomplish.  With a bit of work, I'm formatting the chapters down to 40 columns, with BR> commands at the end of each line.  The use of PETSCII colors from .TML are the spice on top.    However...

A Feature Request:
I'd love to have the ability to use something like a PRE> /PRE> tag which would keep me from having to <BR> each line in the document.  Even better would be having the document "autoformat" to the 40 column resolution without breaking words.   This would be something I'm sure that would require a terminal update.

A Question:
Currently each page of my document looks something like this:
```

Title, page#1<BR>
Story Line 1<BR>
Story Line 2<BR>
Story Line 3<BR>

<KPROMPT t=RETURN>
	<CURSOR>
	<INKEYS>
    <WHITE>
    <BR><CLS>

Title, page#2<BR>
Story Line 1<BR>
Story Line 2<BR>
Story Line 3<BR>
```

How do I incorporate a <- to exit in .TML?   It looks like it may be possible, but unsure.

Thanks

**Comment by retrocomputacion** [comment]
Auto format to the client's screen width is something the server can already do, but not yet from inside a TML script.
I'm thinking of two possible ways to get around this:
Making text_displayer() and or More() functions available from TML, something like:
```
<TEXTDISPLAY f="tmlfile.tml">
```
or a new tag `<FORMAT></FORMAT>` that will autoformat any text inside the tags to the client's screen width. 

For the exit arrow, you can display it with the tag `<BACK>` (You may need to upgrade to the MSX support branch, I dont remember right now if that tag is available on the main branch).
To get the keypress on INKEYS, use '_' in the `k` parameter

**Comment by chriskewl** [comment]
I think this was closed in error since it was not completed yet though maybe I'm wrong. 

Do you have the SEQ version for menus so I can make my own custom menus with PETSCII?

Eventually I'd love a way to use KOALA or other pictures for menus, but I think that's a future item. For now PETSCII would be great.

**Comment by retrocomputacion** [comment]
This issue was for the text auto formatting to the client screen in TML scripts. This is supported now (for commodore only for now), with the FORMAT tag. 
The one for picture menus is this one: https://github.com/retrocomputacion/retrobbs/issues/16
