### ISSUE TITLE
Audio playback at wrong bitrate for 11 kHz, 8-bit mono

### ISSUE THREAD

**Issue by chriskewl** [retrocomputacion/retrobbs#9]
Noticed that you are sending audio at 11520hz, If you are aiming for 11 kHz, 8-bit mono standard then that's 11025hz (transposing the 5 and 0).

The goal is to reduce the extra noise, I'd love to get rid of the skipping sound I hear when a song plays.

You may also check to see if the bitrate is the same, if so then no transcode needed. I'd be glad to set all my audio files to 8-bit mono.

**Comment by retrocomputacion** [comment]
The sample rate is the connection bitrate (57600bps) divided by 10bits (1start bit+8 data bits+1 stop bit) (5760 bytes/s) times 2 (2 4-bit samples per byte) = 11520Hz

The small skipping/stuttering sound that can sometimes can be heard is the Wifi modem sending longer than normal stop bits.

**Comment by chriskewl** [comment]
> The sample rate is the connection bitrate (57600bps) divided by 10bits (1start bit+8 data bits+1 stop bit) (5760 bytes/s) times 2 (2 4-bit samples per byte) = 11520Hz

It has to be that exact number? So this means if there are delays or dropped packets the song will error out potentially?

> The small skipping/stuttering sound that can sometimes can be heard is the Wifi modem sending longer than normal stop bits.

The odd part is that the UII+ at the 7k has no skips at all, it is very smooth sounding. You think there is an issue with Zimodem's firmware?

**Comment by retrocomputacion** [comment]
I found that the stuttering is almost completely gone by compiling the firmware with:

lwIP Variant = "v2 Higher bandwidth"

**Comment by chriskewl** [comment]
> I found that the stuttering is almost completely gone by compiling the firmware with:
> 
> lwIP Variant = "v2 Higher bandwidth"

How do I do that?

Also I sent you a FB message, may be easier to have chats like this on there than on here where it clutters things up.

**Comment by retrocomputacion** [comment]
> > I found that the stuttering is almost completely gone by compiling the firmware with:
> > lwIP Variant = "v2 Higher bandwidth"
> 
> How do I do that?
> 
> Also I sent you a FB message, may be easier to have chats like this on there than on here where it clutters things up.

I didn't get any message on FB, I'm not with my real name there, but you can find me as 'Durandal Woz'

**Comment by chriskewl** [comment]
Going to close this since it isn't a bug. We need to find a proper audio file converter that will do at the exact speed you need or convert on the fly for everything.
